name: AI Coach Production API Testing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://Vishal580.github.io/API-Automation-RestAssured-AI-Coach-Prod"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure

      - name: Run API Tests
        id: test_run
        run: |
          mvn clean test -Dtestng=testng.xml
          ls -l allure-results  # Verify allure-results folder contents

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Checkout gh-pages for Allure History
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Merge Allure History and Generate Report
        run: |
          mkdir -p allure-history
          cp -r gh-pages/allure-history/* allure-results/ || true
          allure generate allure-results --clean -o allure-report
          cp -r allure-report allure-history

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Set Deployment URL
        run: |
          echo "DEPLOYMENT_URL=${{ env.BASE_URL }}/${{ github.run_number }}/index.html" >> $GITHUB_ENV
          echo "Deployment URL: ${{ env.DEPLOYMENT_URL }}"

      - name: Send Email Notification on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: vishalkhetriba@gmail.com
          password: hxuk gvrq oelg lupo
          subject: 'Test Results Notification - API Tests Failed'
          body: |
            The API tests have failed. Review the report:
            ${{ env.DEPLOYMENT_URL }}
          to: vishal@frugaltestingin.com, yogeshk@frugaltesting.com
          from: vishalkhetriba@gmail.com

